version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-v1-{{ checksum "backend/composer.lock" }}
      - run:
          working_directory: backend
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "backend/composer.lock" }}
          paths:
            - backend/vendor
      - restore_cache:
          key: npm-v1-{{ checksum "backend/package-lock.json" }}
      - run:
          working_directory: backend
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "backend/package-lock.json" }}
          paths:
            - backend/node_modules
      - run:
          working_directory: backend
          command: npm run dev
      - run:
          working_directory: backend
          name: php test
          command: vendor/bin/phpunit

  deploy:
    docker:
      - image: circleci/php:7.4-node-browsers

    environment:
      AWS_DEFAULT_REGION: ap-northeast-1

    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-no-dev-v1-{{ checksum "backend/composer.lock" }}
      - run:
          working_directory: backend
          command: composer install -n --no-dev --prefer-dist
      - save_cache:
          key: composer-no-dev-v1-{{ checksum "backend/composer.lock" }}
          paths:
            - backend/vendor
      - restore_cache:
          key: npm-v1-{{ checksum "backend/package-lock.json" }}
      - run:
          working_directory: backend
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "backend/package-lock.json" }}
          paths:
            - backend/node_modules
      - run:
        working_directory: backend
        command: npm run prod
      - run:
          working_directory: backend
          name: archive artifacts
          command: zip -ryq backend.zip .
      - aws-cli/install
      - run:
          working_directory: backend
          name: upload artifacts to s3
          command: aws s3 cp backend.zip s3://${AWS_S3_BUCKET_NAME}
      - run:
          working_directory: backend
          name: deploy to prod
          command: |
            aws deploy create-deployment \
            --application-name news-memo-app \
            --deployment-group-name news-memo-app-deploy-group-1 \
            --s3-location bucket=${AWS_S3_BUCKET_NAME},key=backend.zip,bundleType=zip

orbs:
  aws-cli: circleci/aws-cli@1.0.0
