version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-v1-{{ checksum "backend/composer.lock" }}
      - run:
          working_directory: backend
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "backend/composer.lock" }}
          paths:
            - backend/vendor
      - run:
          working_directory: backend
          command: npm ci
      - run:
          working_directory: backend
          command: npm run dev
      - run:
          working_directory: backend
          name: php test
          command: vendor/bin/phpunit
